name: linux
on: push
jobs:

  linux-armv6:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: arm-unknown-linux-gnueabihf
          toolchain: nightly-2023-05-31
          default: true
      - name: install cross toolchain
        env:
          CFLAGS: "-Os -fno-plt -flto=thin"
          LDFLAGS: "-Os -flto=thin -Wl,--as-needed"
          CARGO_UNSTABLE_SPARSE_REGISTRY: "true"
          RUSTFLAGS: "-C opt-level=s"
          CARGO_FEATURE_YYJSON: "1"
        run: |
          brew tap messense/macos-cross-toolchains
          brew install arm-unknown-linux-gnueabihf

          export CC_arm_unknown_linux_gnueabihf=arm-unknown-linux-gnueabihf-gcc
          export CXX_arm_unknown_linux_gnueabihf=arm-unknown-linux-gnueabihf-g++
          export AR_arm_unknown_linux_gnueabihf=arm-unknown-linux-gnueabihf-ar
          export CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-unknown-linux-gnueabihf-gcc

          pip3 install maturin
          maturin build --release --strip --target arm-unknown-linux-gnueabihf --out dist

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
          retention-days: 1