name: linux
on: push
jobs:

  linux-armv6:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python: [
          { version: '3.7', abi: 'cp37-cp37m' }
        ]
        target: [
          { arch: 'arm-unknown-linux-gnueabihf' },
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python.version }}"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target.arch }}
          toolchain: nightly-2023-05-31
          default: true
      - name: install cross toolchain
        env:
          CFLAGS: "-Os"
          LDFLAGS: "-Os -flto -Wl,--as-needed"
          CARGO_UNSTABLE_SPARSE_REGISTRY: "true"
          RUSTFLAGS: "-C opt-level=s"
          CARGO_FEATURE_YYJSON: "1"
          CC_arm_unknown_linux_gnueabihf: "${{ matrix.target.arch }}-gcc"
          CXX_arm_unknown_linux_gnueabihf: "${{ matrix.target.arch }}-g++"
          AR_arm_unknown_linux_gnueabihf: "${{ matrix.target.arch }}-ar"
          CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER: "${{ matrix.target.arch }}-gcc"
        run: |
          brew tap messense/macos-cross-toolchains
          brew install ${{ matrix.target.arch }}

          pip3 install maturin
          maturin build --release --strip --target ${{ matrix.target.arch }} --out dist -i python${{ matrix.python.version }}

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
          retention-days: 1